# netlify.toml
[build]
  publish = "build"  # Adjust this path according to your build output directory

[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true
